### ISSUE TITLE
Can't get past first cutscene

### ISSUE THREAD

**Issue by Volcanotron** [CookiePLMonster/SilentPatchBully#3]
I cant seem to get past the rockstar video unless I use the normal skipping methods afterwards I cant proceed past the first movie with jimmy and his parents.  
Tried on all sorts of ingame settings and compatibility settings 
supplied in the zip are dmp files and a short video.
https://mega.nz/#!p0sFlYqL!zRNzrKlttZ9Y7q5blhplhcsH1Uxp2GLutq6Avev1mJ4

**Comment by CookiePLMonster** [comment]
I noticed two things:

1) You are using OBS and just noticed a somewhat known issue which might make OBS look like it's causing crashes with Bully, but in fact it's my fault. Try without MiniDumper.asi - I'll fix it and ship and updated version in Build 2.
2) Looks like you are usnig DPI scaling because you showed your game as displaying in top left corner. For the time being, try ticking "Override DPI scaling behaviour". I'll try to work it around from code for the next build, but not sure if that's possible.

**Comment by Volcanotron** [comment]
moving the minidumper allowed me to get past the first cutscene, i ran around the school a bit but didn't play anymore then that

**Comment by CookiePLMonster** [comment]
Please try with MiniDumper I linked in #4

**Comment by Volcanotron** [comment]
Yep, she's all good now champ. i was able to get past the cutscene with your new minidumper

**Comment by CookiePLMonster** [comment]
Build 2 is now out and contains a new MiniDumper, so this one is solved!
