### ISSUE TITLE
Game keeps crashing :(

### ISSUE THREAD

**Issue by Gringa24** [CookiePLMonster/SilentPatchBully#69]
![Screenshot_1](https://user-images.githubusercontent.com/81935374/113524134-0873e700-9583-11eb-985a-03f80475f49a.png)

Hi there! This appears to me after playing for about 10-15 minutes (one game day). I use some skin mods inside the world.img file.

I activated "CustomMemoryMgr = 1" to be able to see what type of error it was.

Without mods I get the same error but after an hour or so. I have Windows 10 64-bit.
How can i fix it?

**Comment by Gringa24** [comment]
[Bully.exe.20210404213739.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/6255759/Bully.exe.20210404213739.zip)

**Comment by Gringa24** [comment]
I can't use any of these mods:
* Mod selector
* Not another selector
Without the game crashing all the time.
(There are several youtubers that use mods and have no CTD problems!)
Nor can I play Bully without mods but with new skins because it also crashes.
I cannot make any modifications to the files:
* PedPop
* pedstats
Because the game also crashes.
Hey man, this game is an unstable cr@p ¯ \ _ (ツ) _ / ¯
In Windows 10 I can only play it without any mod but after an hour or more it crashes as usual.
I love this game very much but it makes me sick every time it crashes.

Will there be a patch in the future to correct these crashes?
Anyone there?

**Comment by xamzy** [comment]
Hey there! amzy here, I do support for this patch. 

A large part of your issue here is using mods - most of the mods you've mentioned are unstable/buggy in a lot of ways that can cause crashes, just due to bad script management. 
Pedpop and Pedstats mods override base values and as such can cause issues as well. 

Despite the readme saying Texture mods are okay, there's still quite a few that have issues. The AE Hud Mod is notorious for doing such a thing, and so I wouldn't be surprised if others are the same. I'm looking into testing everything that I have uploaded on bullymodding.xyz and eventually adding a "Compatible with SilentPatch" marker on each download in the future. 

As for the crashes without any modifications, make sure you're running a completely vanilla retail 1.200 install, cracked or pirated versions can still cause a lot of issues, make sure that your copy is genuine. 
Make sure you're also not running in any compatibility mode, or any weird sandbox form, this can also have adverse effects from previous testing. 

If you still crash once these checks are in place, please upload the *then* most recent crashdump, and we'll look into your issue more deeply. 

Many thanks, 
amzy.

**Comment by Gringa24** [comment]
Oh hi amzy!
First of all I wanted to tell you that I have the Steam version of the game and that I had forgotten to mention that I also had the "HUD of the anniversary edition" mod installed as well: P

This time I reinstalled the game and just put the "Alex RK800" mods on it replacing the characters with their alpha / beta textures and I was able to play without problems.

In brief, the game crashed again as soon as I added:

* The HUD of the AE, (Even if it's only the files that go in the TXD folder, not the ones that go in world.img.)
* Any script mod. (especially to switch characters)
* When I added my modified pedpop and pedstats files there were also crashes.
* Even when I added my lightly modified trigger.img (population) file back the same thing happened.
* When I placed my ide.img file with the bosses using their special moves.

Too bad, how I wish I could play the game without errors with all those modifications. At least for 10-15 minutes I can enjoy even for a little while.

I'll be uploading the dump files if it's useful to you :D

Thanks for answering me, best regards!

**Comment by Gringa24** [comment]
[dump files.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/6275723/dump.files.zip)

**Comment by xamzy** [comment]
Hello again! 

I'm not surprised that it crashed considering the AE HUD mod, but I'm glad you could rectify that with the info provided. 
I can't say I've ever heard of the game crashing that frequently with mods installed. One that doesn't crash the game for example, is my "OneHitKO" mod which you can download [here](https://github.com/xamzy/OneHitKO/releases/tag/3.1) 
So please do try running completely Vanilla and giving that a shot. 

The thing is with this game, is that by overloading it with a lot of mods, it can become unstable, especially where population is involved. 
Your case is certainly unique, and considering you're able to provide crashdumps, I can probably safely assume you've installed it correctly (Although do make sure you're on Build 3, and not using an outdated build) 

I'll continue to help look into this, and see if we can arrive at a conclusion, if not a solution. 

Many thanks for the in-depth information! 
Stay safe :)

**Comment by Gringa24** [comment]
Hello amzy!
I was finally able to find the cause of my constant crashes.
Unfortunately the cause is only any "script mod" (eg: not another selector mod, supermod, faction selector mod, selector mod remake).

What could I do to be able to use at least one mod that allows me to change to another character and to be able to modify the respect of the cliques without crashes?

Thanks a lot for helping me 😊
